# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2.1'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    ports:
      - '3395:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    networks:
      - ecommerce

  ecommerce:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8995:8000'
      - '5173:5173'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
      - PHP_UPLOAD_MAX_FILESIZE=20M
      - PHP_POST_MAX_SIZE=20M
      - PHP_MEMORY_LIMIT=1G
    volumes:
      - './eco:/app'
    depends_on:
      - mariadb
    networks:
      - ecommerce

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8095:80' # Map port 8080 on the host to port 80 in the container
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_myapp
      - UPLOAD_LIMIT=10240K
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge